# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/cleanse/podcast/models/podcast/columns.yaml

# Model Class name
modelClass: Cleanse\Podcast\Models\Podcast

# List Title
title: Manage Podcasts

# Link URL for each record
recordUrl: cleanse/podcast/episodes/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: false

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# Filter widget configuration
filter: config_filter.yaml
